pipeline:
  build:
    image: openjdk:8
    environment:
      - GRADLE_USER_HOME=./.gradle
    commands:
      - mv ./src/main/resources/application.properties.example src/main/resources/application.properties
      - ./gradlew build
    when:
      branch: master
      status: success
  docker:
    when:
      branch: master
      status: success
    image: plugins/docker:1.12
    repo: registry.eorlbruder.de/civbudget
    registry: registry.eorlbruder.de
    tags:
      - latest
    dockerfile: ./Dockerfile
    context: ./
    secrets: [docker_username, docker_password]
  notify:
    image: drillster/drone-email
    when:
      branch: master
      status: [success, failure, changed]
    secrets:
      - source: email_host
        target: email_host
      - source: email_password
        target: email_password
      - source: email
        target: plugin_from
      - source: email
        target: email_username
      - source: email
target: email_recipients